/* eslint-disable react/no-unescaped-entities */

const BestLibraries = () => {
    return (
        <div>
            <h2 className="lg:text-4xl text-2xl font-bold font-serif mt-14 mb-6 text-center">Best Libraries in the World</h2>
            <h3 className="text-center font-serif text-cyan-500 space-y-2">Filled with proverb that inspire persevarance and resiliance in the face of challange, <br /> this library is a source of strength during though time.</h3>


            <div className=" ml-5 mr-5">
                <div className="grid grid-cols-1 lg:grid-cols-2 mt-8 mb-5">
                    <div className="">
                        <h2 className="text-3xl font-bold font-serif">Library of Congress</h2>
                        <h3 className="text-emerald-500 font-bold font-serif text-xl mt-3">Washington, D.C., USA</h3>
                        <p className="text-gray-700 font-serif italic mt-5 text-xs">The Library of Congress, located in Washington, D.C., is the largest library in the world by shelf space <br /> and number of books. It serves as the de facto national library of <br /> the United States and is a symbol of American knowledge and cultural heritage. Founded in 1800, the Library <br /> of Congress was established to serve the United States Congress as a research library. Over the years, its collections have grown exponentially, encompassing a vast array of materials in various formats, including books, manuscripts, maps, <br /> photographs, prints, recordings, and more. The library's mission expanded to include serving as a national library for all Americans, providing access to knowledge and resources for research, education, and cultural enrichment. The library's collection is truly diverse and comprehensive, covering virtually every subject and period of human knowledge. It includes rare and unique items such as the rough draft of the Declaration of Independence, the Gutenberg Bible, the contents of Abraham Lincoln's <br /> pockets on the night of his assassination, and the personal papers of prominent figures like Thomas Jefferson, Rosa Parks, and Sigmund Freud. The Library of Congress is not just a repository of books and documents; it is also a center of scholarship, innovation, and creativity. It hosts numerous exhibitions, lectures, and events that showcase its collections and promote learning <br /> and discovery. Its digital initiatives, including the American Memory project and the National Digital Library Program, make millions of resources accessible online to people around the world. The library's iconic Jefferson Building, with its neoclassical architecture and magnificent interiors adorned with colorful murals and sculptures, is a testament to the importance <br /> of knowledge and culture in American society. It is a place of inspiration and enlightenment, where visitors can explore the richness of human history and imagination.</p>
                    </div>
                    <img className="w-[800px]" src="../../../public/Images/download1.jpg" alt="" />
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 mt-10 gap-5">
                    <img className="w-[800px]" src="../../../public/Images/download (2).jpg" alt="" />
                    <div>
                        <h2 className="text-3xl font-bold font-serif">British Library</h2>
                        <h3 className="text-emerald-500 font-bold font-serif text-xl mt-3">London, UK</h3>
                        <p className="text-gray-700 text-xs font-serif italic mt-5">The British Library, situated in London, is one of the world's largest and most prestigious research libraries. <br /> Its origins can be traced back to the foundation of the British Museum Library in 1753, which later became an <br /> integral part of the British Library upon its establishment in 1973. As the national library of the United Kingdom, the British Library holds a vast and diverse collection of over 200 million items, spanning books, manuscripts, maps, newspapers, prints, drawings, and digital materials. Its holdings cover virtually every aspect of human knowledge and culture, <br /> from ancient artifacts to contemporary works. The centerpiece of the British Library is its iconic St Pancras building, a masterpiece <br /> of modern architecture designed by Sir Colin St John Wilson and opened to the public in 1997. The building's striking design features a dramatic atrium, expansive reading rooms, and state-of-the-art storage facilities that house the library's extensive collections. Among the most prized possessions of the British Library are its historic treasures, including the Magna Carta, the Lindisfarne Gospels, the Gutenberg Bible, and the original manuscript of Lewis Carroll's Alice's Adventures in Wonderland." <br /> These priceless artifacts are carefully preserved and made accessible to researchers, scholars, and the general public. In addition to its physical collections, the British Library is also a leader in digital preservation and access. Its website provides online access to millions of digitized items, allowing users from around the world to explore rare and unique materials remotely. <br /> The British Library is not only a repository of knowledge but also a dynamic center of research, scholarship, and cultural engagement. It hosts exhibitions, events, and educational programs that showcase its collections and promote learning and discovery. It also serves as a hub for collaboration and innovation, fostering partnerships with libraries, <br /> museums, universities, and cultural institutions worldwide.</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 mt-10 gap-5">
                    <div>
                        <h2 className="text-3xl font-bold font-serif">Bibliothèque nationale de France</h2>
                        <h3 className="text-emerald-500 font-bold font-serif text-xl mt-3">Paris, France</h3>
                        <p className="text-gray-700 font-serif italic mt-5 text-xs">The Bibliothèque nationale de France (National Library of France), <br /> located in Paris, is the national library of France and one of the largest and most important <br /> libraries in the world. Established in 1461 by King Louis XI, its mission is to collect, preserve, <br /> and provide access to the nation's cultural and intellectual heritage. The library's collections are vast <br /> and diverse, comprising over 40 million items, including books, manuscripts, maps, prints, photographs, <br /> sound recordings, and digital resources. Its holdings cover a wide range of subjects and periods, <br /> reflecting the richness and diversity of French culture and history. The Bibliothèque nationale de France is housed in several locations across Paris, with its main site located in the 13th arrondissement. The François-Mitterrand Library, named <br /> after the former French president, is the largest and most modern of the library's buildings. Designed by architect Dominique Perrault and opened in 1996, it features four glass towers shaped like open books, symbolizing the pursuit of knowledge and the openness of the library to the public. In addition to the François-Mitterrand Library, the Bibliothèque nationale de France also includes the Richelieu Library, the Arsenal Library, and the Bibliothèque-Musée de l'Opéra. <br /> Each site has its own specialized collections and areas of focus, ranging from rare manuscripts and incunabula to contemporary publications and multimedia resources. The library's collections are complemented by a wide range of services and facilities, including reading rooms, exhibition spaces, lecture halls, and digital resources. It also offers educational programs, research fellowships, and public events that promote scholarship, cultural exchange, <br /> and lifelong learning.As a national institution, the Bibliothèque nationale de France plays a vital role in preserving <br /> and promoting French culture and heritage. It serves as a center of research, scholarship, and cultural enrichment, welcoming visitors from around the world to explore its collections and engage with its resources.</p>
                    </div>
                    <img className="w-[800px]" src="../../../public/Images/images (2).jpg" alt="" />
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 mt-10 gap-5">
                    <img className="w-[800px]" src="../../../public/Images/download (3).jpg" alt="" />
                    <div>
                        <h2 className="text-3xl font-bold font-serif">Stuttgart City Library</h2>
                        <h3 className="text-emerald-500 font-bold font-serif text-xl mt-3">Stuttgart, Germany</h3>
                        <p className="text-gray-700 font-serif italic mt-5 text-xs">The Stuttgart City Library, located in Stuttgart, Germany, is a striking modern architectural <br /> marvel renowned for its innovative design and expansive collection of books and resources. Designed by <br /> the Korean architect Eun Young Yi, the library's minimalist and futuristic cube-shaped structure has <br /> garnered international acclaim since its opening in 2011. Situated in the heart of Stuttgart, the library stands as <br /> a beacon of knowledge and culture, welcoming visitors from near and far to explore its vast collection of books, <br /> magazines, newspapers, and multimedia resources. With over 500,000 items available for loan, as well as numerous <br /> digital resources accessible online, the library offers a wealth of information and inspiration to patrons of all ages and interests. One of the most striking features of the Stuttgart City Library is its luminous interior, flooded with natural light that streams through the glass facade and fills the atrium with warmth and brightness. The open and airy design creates a welcoming and inviting atmosphere, conducive to reading, studying, and contemplation. The library's innovative design extends beyond its architecture to include state-of-the-art facilities and services designed to meet the needs of modern library users. <br /> It features comfortable reading areas, study spaces, computer workstations, and meeting rooms, as well as a dedicated children's section and a multimedia center. In addition to its extensive collection and modern facilities, the Stuttgart City <br /> Library also serves as a cultural hub for the community, hosting a wide range of events, exhibitions, lectures, and workshops throughout the year. From author readings and book signings to art installations and film screenings, <br /> there is always something happening at the library to engage and inspire visitors of all ages.</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BestLibraries;